[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = [
  "dotnet publish -c Release -r linux-x64 --self-contained true -o out"
]

[start]
cmd = "./out/IntegraBrasilApi"